// Generated by npm run build:worker. Edit src/ files, then rebuild.
//#region cloudflare/supabase-proxy/src/const/proxyConfig.ts
var DEFAULT_ALLOWED_ORIGINS = [
  'https://saving-app-dusky.vercel.app',
  'http://127.0.0.1:5173',
  'http://localhost:5173',
];
var FORWARDED_HEADERS = [
  'accept',
  'authorization',
  'apikey',
  'content-type',
  'accept-profile',
  'content-profile',
  'prefer',
  'x-client-info',
  'x-supabase-api-version',
  'x-upsert',
  'cache-control',
  'range',
  'if-none-match',
  'if-modified-since',
];
var EXPOSED_HEADERS =
  'content-range, content-disposition, etag, retry-after, x-saving-proxy';
var PREFLIGHT_MAX_AGE = '3600';
function routeMethods(path) {
  if (
    [
      '/auth/v1/token',
      '/auth/v1/logout',
      '/auth/v1/signup',
      '/auth/v1/recover',
      '/auth/v1/resend',
      '/auth/v1/factors',
    ].includes(path)
  )
    return ['POST'];
  if (path === '/auth/v1/user') return ['GET', 'PUT'];
  if (path === '/auth/v1/settings') return ['GET'];
  if (path === '/auth/v1/verify') return ['GET', 'POST'];
  if (
    /^\/auth\/v1\/factors\/[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}$/i.test(
      path,
    )
  )
    return ['DELETE'];
  if (
    /^\/auth\/v1\/factors\/[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}\/(challenge|verify)$/i.test(
      path,
    )
  )
    return ['POST'];
  if (path === '/rest/v1/workspaces') return ['GET', 'HEAD', 'POST', 'PATCH'];
  return [];
}
//#endregion
//#region cloudflare/supabase-proxy/src/lib/configuration.ts
function upstreamOrigin(env) {
  try {
    const url = new URL(env.SUPABASE_URL?.trim() || '');
    if (
      url.protocol === 'https:' &&
      /^[a-z0-9-]+\.supabase\.co$/.test(url.hostname) &&
      !url.port &&
      !url.username &&
      !url.password &&
      url.pathname === '/' &&
      !url.search &&
      !url.hash
    )
      return url.origin;
  } catch {}
  throw new Error(
    'Set SUPABASE_URL to your original https://PROJECT_REF.supabase.co origin in Worker Settings.',
  );
}
function allowedOrigins(env) {
  if (!env.ALLOWED_ORIGINS?.trim()) return new Set(DEFAULT_ALLOWED_ORIGINS);
  const origins = env.ALLOWED_ORIGINS.split(',')
    .map((value) => value.trim())
    .filter(Boolean);
  try {
    return new Set(
      origins.map((value) => {
        const url = new URL(value);
        if (
          (!(
            url.protocol === 'http:' &&
            ['localhost', '127.0.0.1', '[::1]'].includes(url.hostname)
          ) &&
            url.protocol !== 'https:') ||
          url.username ||
          url.password ||
          url.pathname !== '/' ||
          url.search ||
          url.hash
        )
          throw new Error();
        return url.origin;
      }),
    );
  } catch {
    throw new Error(
      'ALLOWED_ORIGINS must contain comma-separated HTTPS origins without paths. Localhost HTTP is supported.',
    );
  }
}
function allowedCallback(value, origins) {
  try {
    const target = new URL(value);
    return (
      !target.username &&
      !target.password &&
      origins.has(target.origin) &&
      target.pathname === '/account'
    );
  } catch {
    return false;
  }
}
//#endregion
//#region cloudflare/supabase-proxy/src/lib/responses.ts
function responseHeaders(origin, initial) {
  const headers = new Headers(initial);
  for (const name of [...headers.keys()])
    if (name.startsWith('access-control-')) headers.delete(name);
  headers.delete('set-cookie');
  headers.set('Cache-Control', 'private, no-store');
  headers.set('Pragma', 'no-cache');
  headers.set('Expires', '0');
  headers.set('X-Content-Type-Options', 'nosniff');
  headers.set('X-Saving-Proxy', 'cloudflare');
  const vary = new Set(
    (headers.get('Vary') || '')
      .split(',')
      .map((value) => value.trim())
      .filter(Boolean),
  );
  vary.add('Origin');
  headers.set('Vary', [...vary].join(', '));
  if (origin) {
    headers.set('Access-Control-Allow-Origin', origin);
    headers.set('Access-Control-Expose-Headers', EXPOSED_HEADERS);
  }
  return headers;
}
function jsonResponse(body, status, origin) {
  const headers = responseHeaders(origin);
  headers.set('Content-Type', 'application/json; charset=utf-8');
  return new Response(JSON.stringify(body), {
    status,
    headers,
  });
}
function preflight(request, origin, methods) {
  const requestedMethod =
    request.headers.get('Access-Control-Request-Method') || '';
  const requestedHeaders = (
    request.headers.get('Access-Control-Request-Headers') || ''
  )
    .split(',')
    .map((value) => value.trim().toLowerCase())
    .filter(Boolean);
  if (
    !origin ||
    !methods.includes(requestedMethod) ||
    requestedHeaders.some((name) => !FORWARDED_HEADERS.includes(name))
  )
    return jsonResponse(
      { message: 'This browser request method or header is not allowed.' },
      403,
      origin,
    );
  const headers = responseHeaders(origin);
  headers.set('Access-Control-Allow-Methods', methods.join(', '));
  headers.set('Access-Control-Allow-Headers', FORWARDED_HEADERS.join(', '));
  headers.set('Access-Control-Max-Age', PREFLIGHT_MAX_AGE);
  headers.append(
    'Vary',
    'Access-Control-Request-Method, Access-Control-Request-Headers',
  );
  return new Response(null, {
    status: 204,
    headers,
  });
}
//#endregion
//#region cloudflare/supabase-proxy/src/lib/forwardRequest.ts
async function forwardRequest(request, upstream, origin, callbackOrigins) {
  const incoming = new URL(request.url);
  const destination = new URL(upstream);
  destination.pathname = incoming.pathname;
  destination.search = incoming.search;
  const headers = new Headers();
  for (const name of FORWARDED_HEADERS) {
    const value = request.headers.get(name);
    if (value !== null) headers.set(name, value);
  }
  try {
    const response = await fetch(destination.toString(), {
      method: request.method,
      headers,
      body: ['GET', 'HEAD'].includes(request.method) ? void 0 : request.body,
      redirect: 'manual',
      cache: 'no-store',
    });
    const outgoing = responseHeaders(origin, response.headers);
    const location = response.headers.get('Location');
    if (response.status >= 300 && response.status < 400 && location) {
      const target = new URL(location, destination);
      const emailCallback =
        incoming.pathname === '/auth/v1/verify' &&
        allowedCallback(target.href, callbackOrigins);
      if (
        !emailCallback &&
        (target.origin !== upstream || !routeMethods(target.pathname).length)
      ) {
        await response.body?.cancel();
        return jsonResponse(
          { message: 'Supabase returned an unsupported redirect.' },
          502,
          origin,
        );
      }
      if (emailCallback) outgoing.set('Location', target.href);
      else {
        const proxied = new URL(incoming.origin);
        proxied.pathname = target.pathname;
        proxied.search = target.search;
        proxied.hash = target.hash;
        outgoing.set('Location', proxied.toString());
      }
    }
    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers: outgoing,
    });
  } catch {
    return jsonResponse(
      {
        message:
          'The proxy could not reach Supabase. Check the Worker SUPABASE_URL and the Supabase project status.',
      },
      502,
      origin,
    );
  }
}
//#endregion
//#region cloudflare/supabase-proxy/src/index.ts
var src_default = {
  async fetch(request, env) {
    const path = new URL(request.url).pathname;
    const requestedOrigin = request.headers.get('Origin');
    let origin = null;
    let upstream;
    let allowed;
    try {
      allowed = allowedOrigins(env);
      if (requestedOrigin && !allowed.has(requestedOrigin))
        return jsonResponse(
          { message: 'This website origin is not allowed.' },
          403,
          null,
        );
      origin = requestedOrigin;
      upstream = upstreamOrigin(env);
    } catch (reason) {
      const message =
        reason instanceof Error
          ? reason.message
          : 'Invalid Worker configuration.';
      if (path === '/health' && request.method === 'GET')
        return jsonResponse(
          {
            ok: true,
            service: 'saving-app',
            configured: false,
            message,
          },
          200,
          origin,
        );
      return jsonResponse({ message }, 503, origin);
    }
    if (path === '/health' && request.method === 'GET')
      return jsonResponse(
        {
          ok: true,
          service: 'saving-app',
          configured: true,
        },
        200,
        origin,
      );
    const methods = routeMethods(path);
    if (!methods.length)
      return jsonResponse(
        { message: 'This API route is not supported by Saving.' },
        404,
        origin,
      );
    if (request.method === 'OPTIONS')
      return preflight(request, origin, methods);
    if (!methods.includes(request.method))
      return jsonResponse(
        { message: 'This request method is not allowed.' },
        405,
        origin,
      );
    const emailVerification =
      request.method === 'GET' && path === '/auth/v1/verify';
    if (
      emailVerification &&
      !allowedCallback(
        new URL(request.url).searchParams.get('redirect_to') ?? '',
        allowed,
      )
    )
      return jsonResponse(
        {
          message:
            'Use an email link with an allowed Saving /account callback.',
        },
        400,
        origin,
      );
    if (!emailVerification && !request.headers.get('apikey'))
      return jsonResponse(
        { message: 'A Supabase publishable API key is required.' },
        401,
        origin,
      );
    return forwardRequest(request, upstream, origin, allowed);
  },
};
//#endregion
export { src_default as default };
