import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { build } from 'vite';
import { format } from 'prettier';

const root = fileURLToPath(new URL('../', import.meta.url));
const result = await build({
  root,
  configFile: false,
  envDir: false,
  publicDir: false,
  build: {
    write: false,
    target: 'es2022',
    minify: false,
    sourcemap: false,
    lib: {
      entry: fileURLToPath(new URL('../src/index.ts', import.meta.url)),
      formats: ['es'],
      fileName: 'worker',
    },
  },
});
if (!Array.isArray(result) || result.length !== 1)
  throw new Error('Expected one Worker bundle.');
const chunks = result[0].output.filter((entry) => entry.type === 'chunk');
if (chunks.length !== 1 || chunks[0].imports.length)
  throw new Error('The dashboard Worker must be one standalone module.');
const source =
  '// Generated by npm run build:worker. Edit src/ files, then rebuild.\n' +
  chunks[0].code;
await writeFile(
  new URL('../worker.js', import.meta.url),
  await format(source, {
    parser: 'babel',
    tabWidth: 2,
    singleQuote: true,
    semi: true,
    trailingComma: 'all',
    printWidth: 80,
  }),
);
console.log(
  'Created cloudflare/supabase-proxy/worker.js for the Cloudflare dashboard.',
);
